salary_field = '//*[@id="HH-React-Root"]/div/div[3]/div[1]/div/div/div[1]/form/div[11]/div[2]/div[1]/div[1]/fieldset/input'
only_with_salary_field = '//*[@id="HH-React-Root"]/div/div[3]/div[1]/div/div/div[1]/form/div[11]/div[2]/div[2]/label/span'
experience_field = '//*[@id="HH-React-Root"]/div/div[3]/div[1]/div/div/div[1]/form/div[13]/div[2]/div[4]/label/span'
type_field = '//*[@id="HH-React-Root"]/div/div[3]/div[1]/div/div/div[1]/form/div[15]/div[2]/div[1]/label/span'
remote_work_field = '//*[@id="HH-React-Root"]/div/div[3]/div[1]/div/div/div[1]/form/div[17]/div[2]/div[4]/label/span'
search_button_field = '//*[@id="HH-React-Root"]/div/div[3]/div[1]/div/div/div[1]/form/div[29]/div[2]/button'

open_result_url = 'https://samara.hh.ru/vacancy/74137276?from=vacancy_search_list&query=инженер%20по%20тестированию'
apply_button_field = '//*[@id="HH-React-Root"]/div/div[3]/div[1]/div/div/div/div/div[1]/div[1]/div[1]/div/div[3]/div[3]/div/div/a'
outside_field = '//*[@id="HH-React-Root"]/div/div[3]/div[1]'
apply_whole_field = '//*[@id="HH-React-Root"]/div/div[3]/div[1]/div/div/div/div/div[1]/div[4]/div/div[1]/div[2]/div/div[2]'
